#!/bin/bash
### BEGIN INIT INFO
# Provides:          teamcity
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: TeamCity
# Description:       TeamCity
### END INIT INFO
# Source function library.
. /etc/rc.d/init.d/functions
TEAMCITY_USER=teamcity
TEAMCITY_DIR=/var/www/apps/teamcity/TeamCity
TEAMCITY_PATH=$TEAMCITY_DIR/bin/runAll.sh 
#TEAMCITY_DATA_DIR=$TEAMCITY_DIR/.BuildServer
TEAMCITY_DATA_DIR=/home/$TEAMCITY_USER/.BuildServer
case $1 in
    start)
        su - $TEAMCITY_USER -c "TEAMCITY_DATA_PATH=$TEAMCITY_DATA_DIR $TEAMCITY_PATH start"
        ;;
    stop)
        su - $TEAMCITY_USER -c "TEAMCITY_DATA_PATH=$TEAMCITY_DATA_DIR $TEAMCITY_PATH stop"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
